/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ExpiryHelperContract } from "./ExpiryHelper";
import { FeeHelperContract } from "./FeeHelper";
import { HederaTokenServiceContract } from "./HederaTokenService";
import { IHederaTokenServiceContract } from "./IHederaTokenService";
import { KeyHelperContract } from "./KeyHelper";
import { MintingContract } from "./Minting";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ExpiryHelper"): ExpiryHelperContract;
      require(name: "FeeHelper"): FeeHelperContract;
      require(name: "HederaTokenService"): HederaTokenServiceContract;
      require(name: "IHederaTokenService"): IHederaTokenServiceContract;
      require(name: "KeyHelper"): KeyHelperContract;
      require(name: "Minting"): MintingContract;
    }
  }
}

export { ExpiryHelperContract, ExpiryHelperInstance } from "./ExpiryHelper";
export { FeeHelperContract, FeeHelperInstance } from "./FeeHelper";
export {
  HederaTokenServiceContract,
  HederaTokenServiceInstance,
} from "./HederaTokenService";
export {
  IHederaTokenServiceContract,
  IHederaTokenServiceInstance,
} from "./IHederaTokenService";
export { KeyHelperContract, KeyHelperInstance } from "./KeyHelper";
export { MintingContract, MintingInstance } from "./Minting";
