import type { NextPage } from "next";
import Head from "next/head";

const createNft: NextPage = function () {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default createNft;
